import {createSlice} from "@reduxjs/toolkit";
import flatImg from "../assets/img/flat-img.png";
import carImg from "../assets/img/mainBgCardsImg-4.png";
import car2 from "../assets/img/car2.jpg"
import car3 from "../assets/img/car3.jpg"
import car4 from "../assets/img/car4.jpg"
import car5 from "../assets/img/car5.jpg"
import car6 from "../assets/img/car6.jpg"
import car7 from "../assets/img/car7.jpg"
import car8 from "../assets/img/car8.png"
import car9 from "../assets/img/car9.jpg"
import car10 from "../assets/img/car10.jpg"
import car11 from "../assets/img/car11.jpg"
import car12 from "../assets/img/car12.jpg"
import cottage1 from "../assets/img/mainBgCardsImg-2.png";
import cottage2 from "../assets/img/cottage2.jpg";
import cottage3 from "../assets/img/cottage3.jpg";
import cottage4 from "../assets/img/cottage4.jpg";
import cottage5 from "../assets/img/cottage5.jpeg";
import cottage6 from "../assets/img/cottage6.jpg";
import cottage7 from "../assets/img/cottage7.jpg";
import cottage8 from "../assets/img/cottage8.jpg";
import cottage9 from "../assets/img/cottage9.jpg";
import cottage10 from "../assets/img/cottage10.jpg";
import cottage11 from "../assets/img/cottage11.jpg";
import cottage12 from "../assets/img/cottage12.jpg";
import bathImg from "../assets/img/mainBgCardsImg-3.png";
import bath2 from "../assets/img/bath2.jpg";
import bath3 from "../assets/img/bath3.jpg";
import bath4 from "../assets/img/bath4.jpeg";
import bath5 from "../assets/img/bath5.jpeg";
import bath6 from "../assets/img/bath6.jpg";
import bath7 from "../assets/img/bath7.jpg";
import bath8 from "../assets/img/bath8.jpg";
import bath9 from "../assets/img/bath9.jpg";
import bath10 from "../assets/img/bath10.jpg";
import bath11 from "../assets/img/bath11.jpg";
import bath12 from "../assets/img/bath12.jpeg";
import avatar from "../assets/img/avatar.png";
import avatar2 from "../assets/img/avatar2.avif";
import avatar3 from "../assets/img/avatar3.jpg";
import avatar4 from "../assets/img/avatar4.jpg";
import avatar5 from "../assets/img/avatar5.jpg";
import avatar6 from "../assets/img/avatar6.jpg";
import avatar7 from "../assets/img/avatar7.avif";
import avatar8 from "../assets/img/avatar8.avif";
import avatar9 from "../assets/img/avatar9.avif";
import avatar10 from "../assets/img/avatar10.avif";
import avatar11 from "../assets/img/avatar11.jpg";
import avatar12 from "../assets/img/avatar12.jpg";
import new1 from '../assets/img/new-img.png'
import new2  from '../assets/img/new2.jpg'
import new3  from '../assets/img/new3.avif'
import new4  from '../assets/img/new4.jpg'
import new5  from '../assets/img/new5.jpg'
import new6  from '../assets/img/new6.jpg'
import new7  from '../assets/img/new7.jpeg'
import new8  from '../assets/img/new8.jpg'
import new9  from '../assets/img/new9.jpg'
import new10  from '../assets/img/new10.jpg'
import new11  from '../assets/img/new11.png'
import new12  from '../assets/img/new12.jpeg'

const main = createSlice({
    name: 'toolkit',
    initialState:{
        tabs:[{id:'flats', value:'Квартиры'}, {id:'cottages', value:'Котеджы и усадьбы'}, {id:'baths', value:'Бани и сауны'},  {id:'cars', value:'Авто на прокат'}],

        cityOption:[{id:1,value:'Минск'},{id:2,value:'Гомель'},{id:3,value:'Брест'},{id:4,value:'Витебск'},{id:5,value:'Гродно'}, {id:6,value:'Могилев'}],
        cityCurrentValue:'',

        roomsOption: [{id:1,value:1},{id:2,value:2},{id:3,value:3},{id:4,value:4},{id:5,value:5}],
        roomsCurrentValue:'',

        metroOption:[{id:1,value:'Грушевка'},{id:2,value:'Восход'},{id:3,value:'Пушкинская'},{id:4,value:'Партизанская'}],
        metroCurrentValue:'',

        districtOption:[{id:1,value:'Шабаны'},{id:2,value:'Запад'},{id:3,value:'Восток'},{id:4,value:'Малиновка'}],
        districtCurrentValue: '',

        productsLimit: 6,
        currentPage: 1,

        sortedOptions:[{id:1, value:'Сначала дешевые'}, {id:2, value: 'Сначала дорогие'}],
        sortedValue:'',


        bedSum:[{id:1, value:'1'}, {id:2, value:'2'}, {id:3, value:'3'}, {id:4, value:'4'}, {id:5, value:'5'},],
        bedSumCurrentValue:'',

        checkboxsMoreOption:[{id:1, value:'Газовая плита', bol:false},  {id:2, value:'Духовка', bol:false}, {id:3, value:'Кофеварка', bol:false}, {id:4, value:'Микроволновая печь ', bol:false}, {id:5, value:'Посуда', bol:false}, {id:6, value:'Посудомоечная машина', bol:false},],

        minCost:'',
        maxCost:'',


        productsLen: 0,
        sortedProducts:[],
        products: [{
            cars:[
                {id:1, obj:'cars', img:carImg, type:'Gold', rooms:1, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '10.00', metro:'Грушевка', district:'Малиновка', people:'1', title: '-местная. машина', body: 'Идеальный спутник для ваших приключений! Предлагаем вам аренду нашего современного автомобиля с превосходной проходимостью, комфортным салоном и передовыми технологиями. Забронируйте уже сегодня и отправляйтесь в путь без забот!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:2, obj:'cars', img:car2, type:'Gold', rooms:2, city:'Гомель', like:false, location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Партизанская', district:'Запад', people:'2', title: '-местная. машина', body: 'Почувствуйте мощь и комфорт в одном автомобиле! Наша машина готова стать вашим надежным спутником в любых путешествиях: от прогулок по городу до дальних поездок за горизонт. Звоните и арендуйте свой автомобиль прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar2, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:3, obj:'cars', img:car3, type:'Gold', rooms:3, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Грушевка', district:'Малиновка', people:'3', title: '-местная. машина', body: 'Отправляйтесь в путь с комфортом и стилем! Наш автомобиль сочетает в себе элегантный дизайн, высокую проходимость и передовые технологии, чтобы сделать ваше путешествие незабываемым. Забронируйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar3, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:4, obj:'cars', img:car4, type:'Gold', rooms:4, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Партизанская', district:'Запад', people:'4', title: '-местная. машина', body: 'Встречайте новые приключения на нашем автомобиле! Мы предлагаем вам аренду машины с просторным салоном, мощным двигателем и передовыми системами безопасности. Звоните и арендуйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar4, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:5, obj:'cars', img:car5, type:'Gold', rooms:5, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Пушкинская', district:'Восток', people:'5', title: '-местная. машина', body: 'Свобода передвижения в ваших руках! Наш автомобиль готов сделать ваше путешествие удобным и безопасным благодаря своей надежности и комфорту. Забронируйте свой автомобиль прямо сейчас и отправляйтесь в путь без преград!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar5, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:6, obj:'cars', img:car6, type:'Gold', rooms:1, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Грушевка', district:'Запад', people:'1', title: '-местная. машина', body: 'Идеальный выбор для вашего следующего путешествия! Наш автомобиль обеспечит вас комфортом и уверенностью на дороге, а его стильный дизайн станет отличным дополнением к вашему образу. Звоните и арендуйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar6, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:7, obj:'cars', img:car7, type:'Gold', rooms:2, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '60.00', metro:'Партизанская', district:'Восток', people:'2', title: '-местная. машина', body: 'Откройте для себя новые горизонты на нашем автомобиле! Современные технологии и надежность делают его идеальным выбором для ваших путешествий, а комфортный салон придает удовольствие от каждой поездки. Забронируйте свой автомобиль прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar7, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:8, obj:'cars', img:car8, type:'Gold', rooms:3, city:'Гомель', like:false, location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Пушкинская', district:'Запад', people:'3', title: '-местная. машина', body: 'Готовьтесь к приключениям на нашем автомобиле! Мощный двигатель, надежная конструкция и передовые системы безопасности делают его идеальным спутником ваших путешествий. Звоните и арендуйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar8, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:9, obj:'cars', img:car9, type:'Gold', rooms:4, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '70.00', metro:'Партизанская', district:'Шабаны', people:'4', title: '-местная. машина', body: 'Ваше удобство - наш приоритет! Наш автомобиль предлагает вам не только комфорт и безопасность, но и возможность насладиться каждым моментом вашего путешествия благодаря своей функциональности и стилю. Забронируйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar9, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:10, obj:'cars', img:car10, type:'Gold', rooms:5, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Восток', people:'5', title: '-местная. машина', body: 'Путешествуйте с удовольствием на нашем автомобиле! Мы предлагаем вам комфортабельный салон, мощный двигатель и передовые технологии, чтобы сделать ваше путешествие незабываемым. Звоните и арендуйте свой автомобиль прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar10, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:11, obj:'cars', img:car11, type:'Gold', rooms:1, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '85.00', metro:'Восход', district:'Запад', people:'1', title: '-местная. машина', body: 'Ваше удобство на первом месте! Наш автомобиль обеспечит вас комфортом и безопасностью на дороге, а его стильный дизайн придется по вкусу даже самым взыскательным путешественникам. Забронируйте свой автомобиль прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar11, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:12, obj:'cars', img:car12, type:'Gold', rooms:2, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Пушкинская', district:'Шабаны', people:'2', title: '-местная. машина', body: 'Отправляйтесь в путь на нашем автомобиле и наслаждайтесь каждой минутой! У нас вы найдете все необходимое для приятного и беззаботного путешествия: комфортабельный салон, мощный двигатель и передовые технологии. Звоните и арендуйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar12, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:13, obj:'cars', img:car2, type:'Gold', rooms:3, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '120.00', metro:'Восход', district:'Восток', people:'3', title: '-местная. машина', body: 'Идеальный спутник для ваших приключений! Предлагаем вам аренду нашего современного автомобиля с превосходной проходимостью, комфортным салоном и передовыми технологиями. Забронируйте уже сегодня и отправляйтесь в путь без забот!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar2, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:14, obj:'cars', img:car3, type:'Gold', rooms:4, city:'Гомель', like:false, location:'б-р Мулявина, д. 10', cost: '125.00', metro:'Грушевка', district:'Малиновка', people:'4', title: '-местная. машина', body: 'Почувствуйте мощь и комфорт в одном автомобиле! Наша машина готова стать вашим надежным спутником в любых путешествиях: от прогулок по городу до дальних поездок за горизонт. Звоните и арендуйте свой автомобиль прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar3, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:15, obj:'cars', img:car4, type:'Gold', rooms:5, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '45.00', metro:'Пушкинская', district:'Шабаны', people:'5', title: '-местная. машина', body: 'Отправляйтесь в путь с комфортом и стилем! Наш автомобиль сочетает в себе элегантный дизайн, высокую проходимость и передовые технологии, чтобы сделать ваше путешествие незабываемым. Забронируйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar4, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:16, obj:'cars', img:car5, type:'Gold', rooms:1, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'1', title: '-местная. машина', body: 'Встречайте новые приключения на нашем автомобиле! Мы предлагаем вам аренду машины с просторным салоном, мощным двигателем и передовыми системами безопасности. Звоните и арендуйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar5, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:17, obj:'cars', img:car6, type:'Gold', rooms:2, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Пушкинская', district:'Шабаны', people:'2', title: '-местная. машина', body: 'Свобода передвижения в ваших руках! Наш автомобиль готов сделать ваше путешествие удобным и безопасным благодаря своей надежности и комфорту. Забронируйте свой автомобиль прямо сейчас и отправляйтесь в путь без преград!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar6, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:18, obj:'cars', img:car7, type:'Gold', rooms:3, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Партизанская', district:'Малиновка', people:'3', title: '-местная. машина', body: 'Идеальный выбор для вашего следующего путешествия! Наш автомобиль обеспечит вас комфортом и уверенностью на дороге, а его стильный дизайн станет отличным дополнением к вашему образу. Звоните и арендуйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar7, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:19, obj:'cars', img:car8, type:'Gold', rooms:4, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '300.00', metro:'Восход', district:'Запад', people:'4', title: '-местная. машина', body: 'Откройте для себя новые горизонты на нашем автомобиле! Современные технологии и надежность делают его идеальным выбором для ваших путешествий, а комфортный салон придает удовольствие от каждой поездки. Забронируйте свой автомобиль прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar8, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:20, obj:'cars', img:car9, type:'Gold', rooms:5, city:'Гомель', like:false, location:'б-р Мулявина, д. 10', cost: '650.00', metro:'Грушевка', district:'Малиновка', people:'5', title: '-местная. машина', body: 'Готовьтесь к приключениям на нашем автомобиле! Мощный двигатель, надежная конструкция и передовые системы безопасности делают его идеальным спутником ваших путешествий. Звоните и арендуйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar9, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:21, obj:'cars', img:car10, type:'Gold', rooms:1, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-местная. машина', body: 'Ваше удобство - наш приоритет! Наш автомобиль предлагает вам не только комфорт и безопасность, но и возможность насладиться каждым моментом вашего путешествия благодаря своей функциональности и стилю. Забронируйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar10, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:22, obj:'cars', img:car11, type:'Gold', rooms:2, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '70.00', metro:'Восход', district:'Малиновка', people:'2', title: '-местная. машина', body: 'Путешествуйте с удовольствием на нашем автомобиле! Мы предлагаем вам комфортабельный салон, мощный двигатель и передовые технологии, чтобы сделать ваше путешествие незабываемым. Звоните и арендуйте свой автомобиль прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar11, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:23, obj:'cars', img:car12, type:'Gold', rooms:3, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '70.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-местная. машина', body: 'Ваше удобство на первом месте! Наш автомобиль обеспечит вас комфортом и безопасностью на дороге, а его стильный дизайн придется по вкусу даже самым взыскательным путешественникам. Забронируйте свой автомобиль прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar12, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:24, obj:'cars', img:car2, type:'Gold', rooms:4, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Восход', district:'Малиновка', people:'4', title: '-местная. машина', body: 'Отправляйтесь в путь на нашем автомобиле и наслаждайтесь каждой минутой! У нас вы найдете все необходимое для приятного и беззаботного путешествия: комфортабельный салон, мощный двигатель и передовые технологии. Звоните и арендуйте свой автомобиль уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},

            ],

            baths:[
                {id:25, obj:'baths',  img:bathImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'220 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Запад', people:'1', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:26, obj:'baths',  img:bath2, type:'Gold', rooms:2, city:'Гомель', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Запад', people:'2', title: '-комн. баня', body: 'Погрузитесь в атмосферу уюта и релаксации в нашей бане! Предлагаем вам аренду просторной бани с деревянной парной, комнатой отдыха и возможностью заказа дополнительных услуг. Забронируйте уже сегодня и наслаждайтесь заботой о своем теле!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar2, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:27, obj:'baths',  img:bath3, type:'Gold', rooms:3, city:'Бресте', like:false, size:'200 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Малиновка', people:'3', title: '-комн. баня', body: 'Освежите свое тело и душу в нашей уютной бане! У нас вы найдете все необходимое для приятного отдыха: деревянную парную, бассейн, комнату отдыха и возможность заказа массажа. Звоните и бронируйте свое время уже сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar3, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:28, obj:'baths', img:bath4, type:'Gold', rooms:4, city:'Витебске', like:false, size:'200 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Шабаны', people:'4', title: '-комн. баня', body: 'Отдохните и восстановите свои силы в нашей бане! Предлагаем вам аренду просторной бани с уютной парной, комнатой отдыха и возможностью заказа ароматических масел для сауны. Забронируйте свое время прямо сейчас и наслаждайтесь заботой о себе!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar4, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:29, obj:'baths', img:bath5, type:'Gold', rooms:5, city:'Гродно', like:false, size:'200 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Запад', people:'5', title: '-комн. баня', body: 'Наши бани - это идеальное место для отдыха и восстановления! У нас вы найдете все необходимое для приятного времяпрепровождения: деревянные парные, комнаты отдыха и возможность заказа процедур по уходу за телом. Звоните и бронируйте свою баню уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar5, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:30, obj:'baths', img:bath6, type:'Gold', rooms:1, city:'Могилеве', like:false, size:'200 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Запад', people:'1', title: '-комн. баня', body: 'Проведите незабываемый день отдыха в нашей бане! Мы предлагаем вам аренду уютной бани с деревянной парной, комнатой отдыха и возможностью заказа релаксационных процедур. Забронируйте свое время прямо сейчас и наслаждайтесь заботой о себе!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar6, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:31, obj:'baths',  img:bath7, type:'Gold', rooms:2, city:'Минск', like:false, size:'200 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Малиновка', people:'2', title: '-комн. баня', body: 'Отдохните и расслабьтесь в нашей бане после тяжелой недели! У нас вы найдете все необходимое для приятного времяпрепровождения: просторные парные, комнаты отдыха и возможность заказа массажа. Звоните и бронируйте свое время уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar7, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:32, obj:'baths',  img:bath8, type:'Gold', rooms:3, city:'Гомель', like:false, size:'200 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Шабаны', people:'3', title: '-комн. баня', body: 'Погрузитесь в мир релаксации и уюта в нашей бане! Мы предлагаем вам аренду просторных парных, комнат отдыха и возможность заказа ароматических масел для сауны. Забронируйте свое время прямо сейчас и наслаждайтесь заботой о своем теле!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar8, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:33, obj:'baths',  img:bath9, type:'Gold', rooms:4, city:'Бресте', like:false, size:'200 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Запад', people:'4', title: '-комн. баня', body: 'Насладитесь моментами спокойствия и релаксации в нашей бане! У нас вы найдете все, что нужно для приятного отдыха: уютные парные, комнаты отдыха и возможность заказа процедур по уходу за телом. Звоните и бронируйте свое время уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar9, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:34, obj:'baths', img:bath10, type:'Gold', rooms:5, city:'Витебске', like:false, size:'200 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Запад', people:'5', title: '-комн. баня', body: 'Отдохните и ощутите прилив сил в нашей уютной бане! Предлагаем вам аренду просторных парных, комнат отдыха и возможность заказа релаксационных процедур. Забронируйте свое время прямо сейчас и наслаждайтесь заботой о себе!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar10, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:35, obj:'baths', img:bath11, type:'Gold', rooms:1, city:'Гродно', like:false, size:'220 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Малиновка', people:'1', title: '-комн. баня', body: 'Расслабьтесь и забудьте о повседневных заботах в нашей бане! У нас вы найдете все необходимое для приятного отдыха: уютные парные, комнаты отдыха и возможность заказа массажа. Звоните и бронируйте свое время уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar11, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:36, obj:'baths', img:bath12, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'220 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. баня', body: 'Наши бани - это идеальное место для отдыха и восстановления! Мы предлагаем вам аренду просторных парных, комнат отдыха и возможность заказа ароматических масел для сауны. Забронируйте свое время прямо сейчас и наслаждайтесь заботой о себе!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar12, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:37, obj:'baths',  img:bath2, type:'Gold', rooms:3, city:'Минск', like:false, size:'220 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. баня', body: 'Проведите выходные в нашей бане и насладитесь моментами релаксации! У нас вы найдете все необходимое для приятного отдыха: уютные парные, комнаты отдыха и возможность заказа процедур по уходу за телом. Звоните и бронируйте свое время уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:38, obj:'baths',  img:bath3, type:'Gold', rooms:4, city:'Гомель', like:false, size:'220 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Восток', people:'4', title: '-комн. баня', body: 'Погрузитесь в атмосферу уюта и релаксации в нашей бане! Предлагаем вам аренду просторной бани с деревянной парной, комнатой отдыха и возможностью заказа дополнительных услуг. Забронируйте уже сегодня и наслаждайтесь заботой о своем теле!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar2, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:39, obj:'baths',  img:bath4, type:'Gold', rooms:5, city:'Бресте', like:false, size:'220 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Малиновка', people:'5', title: '-комн. баня', body: 'Освежите свое тело и душу в нашей уютной бане! У нас вы найдете все необходимое для приятного отдыха: деревянную парную, бассейн, комнату отдыха и возможность заказа массажа. Звоните и бронируйте свое время уже сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar3, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:40, obj:'baths', img:bath5, type:'Gold', rooms:1, city:'Витебске', like:false, size:'220 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Шабаны', people:'1', title: '-комн. баня', body: 'Отдохните и восстановите свои силы в нашей бане! Предлагаем вам аренду просторной бани с уютной парной, комнатой отдыха и возможностью заказа ароматических масел для сауны. Забронируйте свое время прямо сейчас и наслаждайтесь заботой о себе!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar4, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:41, obj:'baths', img:bath6, type:'Gold', rooms:2, city:'Гродно', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Восток', people:'2', title: '-комн. баня', body: 'Наши бани - это идеальное место для отдыха и восстановления! У нас вы найдете все необходимое для приятного времяпрепровождения: деревянные парные, комнаты отдыха и возможность заказа процедур по уходу за телом. Звоните и бронируйте свою баню уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar5, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:42, obj:'baths', img:bath7, type:'Gold', rooms:3, city:'Могилеве', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. баня', body: 'Проведите незабываемый день отдыха в нашей бане! Мы предлагаем вам аренду уютной бани с деревянной парной, комнатой отдыха и возможностью заказа релаксационных процедур. Забронируйте свое время прямо сейчас и наслаждайтесь заботой о себе!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar6, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:43, obj:'baths',  img:bath8, type:'Gold', rooms:4, city:'Минск', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Малиновка', people:'4', title: '-комн. баня', body: 'Отдохните и расслабьтесь в нашей бане после тяжелой недели! У нас вы найдете все необходимое для приятного времяпрепровождения: просторные парные, комнаты отдыха и возможность заказа массажа. Звоните и бронируйте свое время уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar7, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:44, obj:'baths',  img:bath9, type:'Gold', rooms:5, city:'Гомель', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Шабаны', people:'5', title: '-комн. баня', body: 'Погрузитесь в мир релаксации и уюта в нашей бане! Мы предлагаем вам аренду просторных парных, комнат отдыха и возможность заказа ароматических масел для сауны. Забронируйте свое время прямо сейчас и наслаждайтесь заботой о своем теле!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar8, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:45, obj:'baths',  img:bath10, type:'Gold', rooms:1, city:'Бресте', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Восток', people:'1', title: '-комн. баня', body: 'Насладитесь моментами спокойствия и релаксации в нашей бане! У нас вы найдете все, что нужно для приятного отдыха: уютные парные, комнаты отдыха и возможность заказа процедур по уходу за телом. Звоните и бронируйте свое время уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar9, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:46, obj:'baths', img:bath11, type:'Gold', rooms:2, city:'Витебске', like:false, size:'215 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Восток', people:'2', title: '-комн. баня', body: 'Отдохните и ощутите прилив сил в нашей уютной бане! Предлагаем вам аренду просторных парных, комнат отдыха и возможность заказа релаксационных процедур. Забронируйте свое время прямо сейчас и наслаждайтесь заботой о себе!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar10, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:47, obj:'baths', img:bath12, type:'Gold', rooms:3, city:'Гродно', like:false, size:'215 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Малиновка', people:'3', title: '-комн. баня', body: 'Расслабьтесь и забудьте о повседневных заботах в нашей бане! У нас вы найдете все необходимое для приятного отдыха: уютные парные, комнаты отдыха и возможность заказа массажа. Звоните и бронируйте свое время уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar11, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:48, obj:'baths', img:bath2, type:'Gold', rooms:4, city:'Могилеве', like:false, size:'215 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Шабаны', people:'4', title: '-комн. баня', body: 'Наши бани - это идеальное место для отдыха и восстановления! Мы предлагаем вам аренду просторных парных, комнат отдыха и возможность заказа ароматических масел для сауны. Забронируйте свое время прямо сейчас и наслаждайтесь заботой о себе!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar12, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},

            ],

            cottages:[
                {id:49, obj:'cottages', img:cottage1, type:'Gold', rooms:1, city:'Минск', like:false, size:'215 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'1', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:50, obj:'cottages', img:cottage2, type:'Gold', rooms:2, city:'Гомель', like:false, size:'215 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'2', title: '-комн. коттедж', body: 'Роскошный коттедж для вашего идеального отдыха! Предлагаем просторный дом с современным дизайном, большим участком и всеми удобствами для комфортного проживания. Забронируйте уже сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar2, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:51, obj:'cottages', img:cottage3, type:'Gold', rooms:3, city:'Бресте', like:false, size:'215 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'3', title: '-комн. коттедж', body: 'Идеальное место для уединенного отдыха! Наш коттедж расположен в живописном месте, вдали от городской суеты, с прекрасным видом на природу. Звоните и планируйте свой отдых уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar3, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:52, obj:'cottages', img:cottage4, type:'Gold', rooms:4, city:'Витебске', like:false, size:'215 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'4', title: '-комн. коттедж', body: 'Коттеджный комплекс для ценителей комфорта! У нас вы найдете стильные дома с просторными террасами, собственными бассейнами и зонами отдыха на природе. Поторопитесь забронировать свой уголок рая!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar4, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:53, obj:'cottages', img:cottage5, type:'Gold', rooms:5, city:'Гродно', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'5', title: '-комн. коттедж', body: 'Отдыхайте в окружении роскоши и уюта! Наш коттедж предлагает вам роскошные интерьеры, ухоженные сады и возможность насладиться природой, не отходя далеко от дома. Звоните и узнайте о доступных датам!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar5, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:54, obj:'cottages', img:cottage6, type:'Gold', rooms:1, city:'Могилеве', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. коттедж', body: 'Идеальное место для семейного отдыха! Наш коттеджный комплекс предлагает вам комфортные дома с несколькими спальнями, игровыми комнатами и просторными зонами для отдыха на свежем воздухе. Забронируйте уже сейчас и создайте незабываемые воспоминания!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar6, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:55, obj:'cottages', img:cottage7, type:'Gold', rooms:2, city:'Минск', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'2', title: '-комн. коттедж', body: 'Коттедж на берегу озера – идеальное место для рыбалки и отдыха! У нас вы найдете уютные дома с выходом к воде, а также возможностью аренды лодок и каяков. Планируйте свой отдых прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar7, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:56, obj:'cottages', img:cottage8, type:'Gold', rooms:3, city:'Гомель', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'3', title: '-комн. коттедж', body: 'Романтический уикенд в коттедже на природе! Предлагаем вам уютные дома с каминами, джакузи под открытым небом и возможностью устроить романтические ужины на свежем воздухе. Звоните и бронируйте свой отдых прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar8, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:57, obj:'cottages', img:cottage9, type:'Gold', rooms:4, city:'Бресте', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'4', title: '-комн. коттедж', body: 'Коттедж для активного отдыха на природе! Наш комплекс предлагает вам возможность заняться различными видами активного отдыха, включая пешие прогулки, велосипедные прогулки и лыжные прогулки. Забронируйте свой дом уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar9, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:58, obj:'cottages', img:cottage10, type:'Gold', rooms:5, city:'Витебске', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'5', title: '-комн. коттедж', body: 'Уютный коттедж для вашего спокойного отдыха! Предлагаем вам уединенные дома с просторными террасами, где вы сможете насладиться тишиной и покоем в окружении природы. Звоните и выбирайте свой идеальный уголок отдыха!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar10, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:59, obj:'cottages', img:cottage11, type:'Gold', rooms:1, city:'Гродно', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'1', title: '-комн. коттедж', body: 'Коттедж на берегу моря – идеальное место для летнего отдыха! Наш комплекс предлагает вам уютные дома с прямым доступом к пляжу, а также инфраструктуру для пляжного отдыха и различных видов активного отдыха на воде. Звоните и бронируйте уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar11, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:60, obj:'cottages', img:cottage12, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. коттедж', body: 'Коттедж в горах – идеальное место для зимнего отдыха! У нас вы найдете уютные дома с каминами, саунами и прекрасным видом на горы, а также возможностью заняться лыжным спортом и сноубордингом. Звоните и запланируйте свой зимний отдых уже сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar12, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:61, obj:'cottages', img:cottage1, type:'Gold', rooms:3, city:'Минск', like:false, size:'210 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. коттедж', body: 'Роскошный коттедж для вашего идеального отдыха! Предлагаем просторный дом с современным дизайном, большим участком и всеми удобствами для комфортного проживания. Забронируйте уже сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar2, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:62, obj:'cottages', img:cottage2, type:'Gold', rooms:4, city:'Гомель', like:false, size:'240 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'4', title: '-комн. коттедж', body: 'Идеальное место для уединенного отдыха! Наш коттедж расположен в живописном месте, вдали от городской суеты, с прекрасным видом на природу. Звоните и планируйте свой отдых уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar3, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:63, obj:'cottages', img:cottage3, type:'Gold', rooms:5, city:'Бресте', like:false, size:'240 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'5', title: '-комн. коттедж', body: 'Коттеджный комплекс для ценителей комфорта! У нас вы найдете стильные дома с просторными террасами, собственными бассейнами и зонами отдыха на природе. Поторопитесь забронировать свой уголок рая!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar4, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:64, obj:'cottages', img:cottage4, type:'Gold', rooms:1, city:'Витебске', like:false, size:'240 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'1', title: '-комн. коттедж', body: 'Отдыхайте в окружении роскоши и уюта! Наш коттедж предлагает вам роскошные интерьеры, ухоженные сады и возможность насладиться природой, не отходя далеко от дома. Звоните и узнайте о доступных датам!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar5, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:65, obj:'cottages', img:cottage5, type:'Gold', rooms:2, city:'Гродно', like:false, size:'240 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'2', title: '-комн. коттедж', body: 'Идеальное место для семейного отдыха! Наш коттеджный комплекс предлагает вам комфортные дома с несколькими спальнями, игровыми комнатами и просторными зонами для отдыха на свежем воздухе. Забронируйте уже сейчас и создайте незабываемые воспоминания!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar6, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:66, obj:'cottages', img:cottage6, type:'Gold', rooms:3, city:'Могилеве', like:false, size:'235 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'3', title: '-комн. коттедж', body: 'Коттедж на берегу озера – идеальное место для рыбалки и отдыха! У нас вы найдете уютные дома с выходом к воде, а также возможностью аренды лодок и каяков. Планируйте свой отдых прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar7, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:67, obj:'cottages', img:cottage7, type:'Gold', rooms:4, city:'Минск', like:false, size:'235 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'4', title: '-комн. коттедж', body: 'Романтический уикенд в коттедже на природе! Предлагаем вам уютные дома с каминами, джакузи под открытым небом и возможностью устроить романтические ужины на свежем воздухе. Звоните и бронируйте свой отдых прямо сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar8, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:68, obj:'cottages', img:cottage8, type:'Gold', rooms:5, city:'Гомель', like:false, size:'235 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'5', title: '-комн. коттедж', body: 'Коттедж для активного отдыха на природе! Наш комплекс предлагает вам возможность заняться различными видами активного отдыха, включая пешие прогулки, велосипедные прогулки и лыжные прогулки. Забронируйте свой дом уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar9, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:69, obj:'cottages', img:cottage9, type:'Gold', rooms:1, city:'Бресте', like:false, size:'235 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. коттедж', body: 'Уютный коттедж для вашего спокойного отдыха! Предлагаем вам уединенные дома с просторными террасами, где вы сможете насладиться тишиной и покоем в окружении природы. Звоните и выбирайте свой идеальный уголок отдыха!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar10, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:70, obj:'cottages', img:cottage10, type:'Gold', rooms:2, city:'Витебске', like:false, size:'235 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'2', title: '-комн. коттедж', body: 'Коттедж на берегу моря – идеальное место для летнего отдыха! Наш комплекс предлагает вам уютные дома с прямым доступом к пляжу, а также инфраструктуру для пляжного отдыха и различных видов активного отдыха на воде. Звоните и бронируйте уже сегодня!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar11, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:71, obj:'cottages', img:cottage11, type:'Gold', rooms:3, city:'Гродно', like:false, size:'235 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-комн. коттедж', body: 'Коттедж в горах – идеальное место для зимнего отдыха! У нас вы найдете уютные дома с каминами, саунами и прекрасным видом на горы, а также возможностью заняться лыжным спортом и сноубордингом. Звоните и запланируйте свой зимний отдых уже сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar12, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:72, obj:'cottages', img:cottage12, type:'Gold', rooms:4, city:'Могилеве', like:false, size:'225 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'4', title: '-комн. коттедж', body: 'Роскошный коттедж для вашего идеального отдыха! Предлагаем просторный дом с современным дизайном, большим участком и всеми удобствами для комфортного проживания. Забронируйте уже сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
            ],

            flats:[
                {id:73, obj:'flats', img:flatImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'132 м²',location:'б-р Мулявина, д. 10', cost: '15.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:74, obj:'flats', img:new1, type:'Gold', rooms:2, city:'Минск', like:false, size:'131 м²',location:'б-р Мулявина, д. 11', cost: '35.00', metro:'Грушевка', district:'Запад', people:'2', title: '-комн. апартаменты', body: 'Превосходное жилье для вашего комфорта! Сдаем современные квартиры в центре города с отличным ремонтом и всей необходимой мебелью. Звоните прямо сейчас, чтобы забронировать свое идеальное жилье!', profile: {name: 'Владимир', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar2, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:75, obj:'flats', img:new2, type:'Gold', rooms:3, city:'Минск', like:false, size:'120 м²',location:'б-р Мулявина, д. 12', cost: '45.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. апартаменты', body: 'Ищете квартиру с видом на море? Мы предлагаем вам роскошные апартаменты с панорамными окнами и прекрасным видом на водную гладь. Поторопитесь забронировать, количество мест ограничено!', profile: {name: 'Данил', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar3, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:76, obj:'flats', img:new3, type:'Gold', rooms:4, city:'Минск', like:false, size:'120 м²',location:'б-р Мулявина, д. 13', cost: '55.00', metro:'Грушевка', district:'Малиновка', people:'4', title: '-комн. апартаменты', body: 'Для тех, кто ценит уют и комфорт! У нас вы найдете просторные квартиры с современным дизайном и всеми удобствами для комфортного проживания. Звоните и запишитесь на просмотр уже сегодня!', profile: {name: 'Александр', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar4, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:77, obj:'flats', img:new4, type:'Gold', rooms:5, city:'Минск', like:false, size:'120 м²',location:'б-р Мулявина, д. 14', cost: '60.00', metro:'Восход', district:'Шабаны', people:'5', title: '-комн. апартаменты', body: 'Аренда жилья для студентов – это легко и выгодно! У нас есть отличные варианты студий и однокомнатных квартир, рядом с университетами и транспортом. Не упустите свой шанс на комфортное проживание во время учебы!', profile: {name: 'Василий', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar5, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:78, obj:'flats', img:new5, type:'Gold', rooms:1, city:'Минск', like:false, size:'140 м²',location:'б-р Мулявина, д. 15', cost: '50.00', metro:'Восход', district:'Запад', people:'1', title: '-комн. апартаменты', body: 'Отличное предложение для семейного проживания! Мы предлагаем просторные апартаменты с несколькими спальнями, большими кухнями и уютными гостинными. Звоните и узнайте о специальных условиях для семейных арендаторов!', profile: {name: 'Сергей', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar6, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:79, obj:'flats', img:new6, type:'Gold', rooms:2, city:'Минск', like:false, size:'140 м²',location:'б-р Мулявина, д. 3', cost: '30.00', metro:'Восход', district:'Восток', people:'2', title: '-комн. апартаменты', body: 'Хотите жить в сердце города? У нас есть идеальное предложение для вас! Сдаем уютные квартиры в центре, рядом с культурными и развлекательными заведениями. Звоните и выбирайте свое идеальное жилье уже сегодня!', profile: {name: 'Никита', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar7, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:80, obj:'flats', img:new7, type:'Gold', rooms:3, city:'Минск', like:false, size:'145 м²',location:'б-р Мулявина, д. 2', cost: '21.00', metro:'Восход', district:'Малиновка', people:'3', title: '-комн. апартаменты', body: 'Апартаменты с шикарным интерьером и превосходным сервисом! У нас вы найдете квартиры, полностью оборудованные всем необходимым для комфортного проживания. Звоните и бронируйте уже сейчас!', profile: {name: 'Илья', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar8, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:81, obj:'flats', img:new8, type:'Gold', rooms:4, city:'Минск', like:false, size:'145 м²',location:'б-р Мулявина, д. 1', cost: '34.00', metro:'Пушкинская', district:'Шабаны', people:'4', title: '-комн. апартаменты', body: 'Для тех, кто ценит свое время и комфорт! Наши квартиры предлагают все удобства современной жизни: от высокоскоростного интернета до круглосуточной охраны. Звоните и узнайте о специальных условиях аренды!', profile: {name: 'Никита', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar9, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:82, obj:'flats', img:new9, type:'Gold', rooms:5, city:'Минск', like:false, size:'145 м²',location:'б-р Мулявина, д. 5', cost: '49.00', metro:'Пушкинская', district:'Запад', people:'5', title: '-комн. апартаменты', body: 'Просторные апартаменты для активного образа жизни! У нас вы найдете квартиры с близостью к паркам, спортивным клубам и зонам отдыха. Звоните и выбирайте свое идеальное жилье для активного образа жизни!', profile: {name: 'Ваня', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar10, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:83, obj:'flats', img:new10, type:'Gold', rooms:1, city:'Минск', like:false, size:'165 м²',location:'б-р Мулявина, д. 6', cost: '50.00', metro:'Пушкинская', district:'Восток', people:'1', title: '-комн. апартаменты', body: 'Идеальное жилье для вашего бизнеса! Мы предлагаем комфортные квартиры с отдельными рабочими зонами и высокоскоростным интернетом. Звоните и узнайте о специальных условиях для бизнес-арендаторов!', profile: {name: 'Егор', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar11, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:84, obj:'flats', img:new11, type:'Gold', rooms:2, city:'Минск', like:false, size:'165 м²',location:'б-р Мулявина, д. 12', cost: '65.00', metro:'Пушкинская', district:'Малиновка', people:'2', title: '-комн. апартаменты', body: 'Ваш уголок спокойствия в шумном мегаполисе! У нас вы найдете квартиры в тихих и зеленых районах города, идеальные для тех, кто ценит уединение и покой. Звоните и запишитесь на просмотр уже сегодня!', profile: {name: 'Егор', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar12, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:85, obj:'flats', img:new12, type:'Gold', rooms:3, city:'Минск', like:false, size:'125 м²',location:'б-р Мулявина, д. 15', cost: '50.00', metro:'Партизанская', district:'Шабаны', people:'3', title: '-комн. апартаменты', body: 'Превосходное жилье для вашего комфорта! Сдаем современные квартиры в центре города с отличным ремонтом и всей необходимой мебелью. Звоните прямо сейчас, чтобы забронировать свое идеальное жилье!', profile: {name: 'Егор', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:86, obj:'flats', img:new1, type:'Gold', rooms:4, city:'Минск', like:false, size:'115 м²',location:'б-р Мулявина, д. 14', cost: '80.00', metro:'Партизанская', district:'Запад', people:'4', title: '-комн. апартаменты', body: 'Ищете квартиру с видом на море? Мы предлагаем вам роскошные апартаменты с панорамными окнами и прекрасным видом на водную гладь. Поторопитесь забронировать, количество мест ограничено!', profile: {name: 'Дмитрий', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar2, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:87, obj:'flats', img:new2, type:'Gold', rooms:5, city:'Минск', like:false, size:'175 м²',location:'б-р Мулявина, д. 13', cost: '65.00', metro:'Партизанская', district:'Восток', people:'5', title: '-комн. апартаменты', body: 'Для тех, кто ценит уют и комфорт! У нас вы найдете просторные квартиры с современным дизайном и всеми удобствами для комфортного проживания. Звоните и запишитесь на просмотр уже сегодня!', profile: {name: 'Даннил', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar3, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:88, obj:'flats', img:new3, type:'Gold', rooms:1, city:'Минск', like:false, size:'185 м²',location:'б-р Мулявина, д. 12', cost: '100.00', metro:'Партизанская', district:'Малиновка', people:'1', title: '-комн. апартаменты', body: 'Аренда жилья для студентов – это легко и выгодно! У нас есть отличные варианты студий и однокомнатных квартир, рядом с университетами и транспортом. Не упустите свой шанс на комфортное проживание во время учебы!', profile: {name: 'Кирилл', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar4, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:89, obj:'flats', img:new4, type:'Gold', rooms:2, city:'Минск', like:false, size:'125 м²',location:'б-р Мулявина, д. 11', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Отличное предложение для семейного проживания! Мы предлагаем просторные апартаменты с несколькими спальнями, большими кухнями и уютными гостинными. Звоните и узнайте о специальных условиях для семейных арендаторов!', profile: {name: 'Кирилл', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar5, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:90, obj:'flats', img:new5, type:'Gold', rooms:4, city:'Гомель', like:false, size:'135 м²',location:'б-р Мулявина, д. 12', cost: '34.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-комн. апартаменты', body: 'Хотите жить в сердце города? У нас есть идеальное предложение для вас! Сдаем уютные квартиры в центре, рядом с культурными и развлекательными заведениями. Звоните и выбирайте свое идеальное жилье уже сегодня!', profile: {name: 'Егор', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar6, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:91, obj:'flats', img:new6, type:'Gold', rooms:5, city:'Гомель', like:false, size:'140 м²',location:'б-р Мулявина, д. 13', cost: '49.00', metro:'Восход', district:'Запад', people:'4', title: '-комн. апартаменты', body: 'Апартаменты с шикарным интерьером и превосходным сервисом! У нас вы найдете квартиры, полностью оборудованные всем необходимым для комфортного проживания. Звоните и бронируйте уже сейчас!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar7, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:92, obj:'flats', img:new7, type:'Gold', rooms:1, city:'Бресте', like:false, size:'150 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Пушкинская', district:'Восток', people:'5', title: '-комн. апартаменты', body: 'Для тех, кто ценит свое время и комфорт! Наши квартиры предлагают все удобства современной жизни: от высокоскоростного интернета до круглосуточной охраны. Звоните и узнайте о специальных условиях аренды!', profile: {name: 'Александр', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar8, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:93, obj:'flats', img:new8, type:'Gold', rooms:2, city:'Бресте', like:false, size:'150 м²',location:'б-р Мулявина, д. 5', cost: '65.00', metro:'Восход', district:'Малиновка', people:'1', title: '-комн. апартаменты', body: 'Просторные апартаменты для активного образа жизни! У нас вы найдете квартиры с близостью к паркам, спортивным клубам и зонам отдыха. Звоните и выбирайте свое идеальное жилье для активного образа жизни!', profile: {name: 'Никита', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar9, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:94, obj:'flats', img:new9, type:'Gold', rooms:3, city:'Витебске', like:false, size:'150 м²',location:'б-р Мулявина, д. 4', cost: '50.00', metro:'Партизанская', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Идеальное жилье для вашего бизнеса! Мы предлагаем комфортные квартиры с отдельными рабочими зонами и высокоскоростным интернетом. Звоните и узнайте о специальных условиях для бизнес-арендаторов!', profile: {name: 'Лев', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar10, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:95, obj:'flats', img:new10, type:'Gold', rooms:4, city:'Витебске', like:false, size:'150 м²',location:'б-р Мулявина, д. 3', cost: '80.00', metro:'Партизанская', district:'Запад', people:'3', title: '-комн. апартаменты', body: 'Ваш уголок спокойствия в шумном мегаполисе! У нас вы найдете квартиры в тихих и зеленых районах города, идеальные для тех, кто ценит уединение и покой. Звоните и запишитесь на просмотр уже сегодня!', profile: {name: 'Дмитрий', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar11, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:96, obj:'flats', img:new11, type:'Gold', rooms:5, city:'Гродно', like:false, size:'150 м²',location:'б-р Мулявина, д. 20', cost: '65.00', metro:'Грушевка', district:'Восток', people:'4', title: '-комн. апартаменты', body: 'Превосходное жилье для вашего комфорта! Сдаем современные квартиры в центре города с отличным ремонтом и всей необходимой мебелью. Звоните прямо сейчас, чтобы забронировать свое идеальное жилье!', profile: {name: 'Лев', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar12, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:97, obj:'flats', img:new12, type:'Gold', rooms:1, city:'Гродно', like:false, size:'130 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Партизанская', district:'Малиновка', people:'5', title: '-комн. апартаменты', body: 'Ищете квартиру с видом на море? Мы предлагаем вам роскошные апартаменты с панорамными окнами и прекрасным видом на водную гладь. Поторопитесь забронировать, количество мест ограничено!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar2, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:98, obj:'flats', img:flatImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'135 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. апартаменты', body: 'Для тех, кто ценит уют и комфорт! У нас вы найдете просторные квартиры с современным дизайном и всеми удобствами для комфортного проживания. Звоните и запишитесь на просмотр уже сегодня!', profile: {name: 'Лев', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar3, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:99, obj:'flats', img:new1, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'135 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Аренда жилья для студентов – это легко и выгодно! У нас есть отличные варианты студий и однокомнатных квартир, рядом с университетами и транспортом. Не упустите свой шанс на комфортное проживание во время учебы!', profile: {name: 'Даннил', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar4, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:100, obj:'flats', img:new2, type:'Gold', rooms:4, city:'Гомель', like:false, size:'125 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-комн. апартаменты', body: 'Отличное предложение для семейного проживания! Мы предлагаем просторные апартаменты с несколькими спальнями, большими кухнями и уютными гостинными. Звоните и узнайте о специальных условиях для семейных арендаторов!', profile: {name: 'Даннил', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar5, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:101, obj:'flats', img:new3, type:'Gold', rooms:5, city:'Гомель', like:false, size:'125 м²',location:'б-р Мулявина, д. 10', cost: '49.00', metro:'Восход', district:'Запад', people:'4', title: '-комн. апартаменты', body: 'Хотите жить в сердце города? У нас есть идеальное предложение для вас! Сдаем уютные квартиры в центре, рядом с культурными и развлекательными заведениями. Звоните и выбирайте свое идеальное жилье уже сегодня!', profile: {name: 'Лев', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar6, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:102, obj:'flats', img:new4, type:'Gold', rooms:1, city:'Бресте', like:false, size:'125 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Пушкинская', district:'Восток', people:'5', title: '-комн. апартаменты', body: 'Апартаменты с шикарным интерьером и превосходным сервисом! У нас вы найдете квартиры, полностью оборудованные всем необходимым для комфортного проживания. Звоните и бронируйте уже сейчас!', profile: {name: 'Дмитрий', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar7, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:103, obj:'flats', img:new5, type:'Gold', rooms:2, city:'Бресте', like:false, size:'125 м²',location:'б-р Мулявина, д. 12', cost: '65.00', metro:'Восход', district:'Малиновка', people:'1', title: '-комн. апартаменты', body: 'Для тех, кто ценит свое время и комфорт! Наши квартиры предлагают все удобства современной жизни: от высокоскоростного интернета до круглосуточной охраны. Звоните и узнайте о специальных условиях аренды!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar8, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:104, obj:'flats', img:new6, type:'Gold', rooms:3, city:'Витебске', like:false, size:'120 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Партизанская', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Просторные апартаменты для активного образа жизни! У нас вы найдете квартиры с близостью к паркам, спортивным клубам и зонам отдыха. Звоните и выбирайте свое идеальное жилье для активного образа жизни!', profile: {name: 'Даннил', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar9, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:105, obj:'flats', img:new7, type:'Gold', rooms:4, city:'Витебске', like:false, size:'120 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Партизанская', district:'Запад', people:'3', title: '-комн. апартаменты', body: 'Идеальное жилье для вашего бизнеса! Мы предлагаем комфортные квартиры с отдельными рабочими зонами и высокоскоростным интернетом. Звоните и узнайте о специальных условиях для бизнес-арендаторов!', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar10, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:106, obj:'flats', img:new8, type:'Gold', rooms:5, city:'Гродно', like:false, size:'120 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Грушевка', district:'Восток', people:'4', title: '-комн. апартаменты', body: 'Ваш уголок спокойствия в шумном мегаполисе! У нас вы найдете квартиры в тихих и зеленых районах города, идеальные для тех, кто ценит уединение и покой. Звоните и запишитесь на просмотр уже сегодня!', profile: {name: 'Василий', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar11, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:107, obj:'flats', img:new9, type:'Gold', rooms:1, city:'Гродно', like:false, size:'120 м²',location:'б-р Мулявина, д. 14', cost: '100.00', metro:'Партизанская', district:'Малиновка', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar12, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:108, obj:'flats', img:new10, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'120 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. апартаменты', body: 'Хотите жить в сердце города? У нас есть идеальное предложение для вас! Сдаем уютные квартиры в центре, рядом с культурными и развлекательными заведениями. Звоните и выбирайте свое идеальное жилье уже сегодня!', profile: {name: 'Сергей', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:109, obj:'flats', img:new11, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'120 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Для тех, кто ценит свое время и комфорт! Наши квартиры предлагают все удобства современной жизни: от высокоскоростного интернета до круглосуточной охраны. Звоните и узнайте о специальных условиях аренды!', profile: {name: 'Сергей', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar2, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},

            ],
        }],

    },
    reducers: {

        setBedSum(state, action){
            state.bedSumCurrentValue = action.payload
        },

        checkboxHandler(state, action){
            state.checkboxsMoreOption.forEach(obj =>{
                if(obj.value.includes(action.payload)){
                    obj.bol = !obj.bol

                }
            })
        },

        likeHandler(state, action){
            state.products.forEach(obj=>{
                Object.keys(obj).forEach(key=>{
                    if(key === action.payload.type){
                        obj[key].forEach(e=>{
                            if (e.id === action.payload.id){
                                e.like = !e.like
                            }
                        })
                    }
                })
            })
        },
        setCity(state, action){
            state.cityCurrentValue = action.payload

        },
        setRooms(state, action){
            state.roomsCurrentValue = action.payload
        },
        setMinCost(state, action){
            if(action.payload<0 || action.payload > 1000){
                return
            }
            state.minCost = action.payload
        },
        setMaxCost(state, action){
            if(action.payload<0 || action.payload > 1000){
                return
            }
            state.maxCost = action.payload
        },
        setDistrict(state, action){
            state.districtCurrentValue = action.payload
        },
        setMetro(state, action){
            state.metroCurrentValue = action.payload
        },
        setCurrentPage(state, action){
            state.currentPage = action.payload
            window.scrollTo(0, 0)
        },
        setSortedValue(state, action){
            state.sortedValue = action.payload
        },

        setLimit(state, action){
            state.productsLimit = action.payload
        },
        resetFilter(state){
            state.sortedValue = ''
            state.roomsCurrentValue = ''
            state.minCost = ''
            state.maxCost = ''
            state.districtCurrentValue = ''
            state.metroCurrentValue = ''
            state.bedSumCurrentValue = ''
            state.checkboxsMoreOption.forEach(e=>{
                e.bol = false
            })
        },

        mainFilter(state, action){
            // Условия для высчитывания стоимости
            while(state.minCost > state.maxCost ){
                state.maxCost = +state.maxCost + 100
            }
            if(state.minCost === ''){
                state.minCost=0
            }
            if(state.maxCost === ''){
                state.maxCost = 1000
            }


            //Основная фильтрация
            let sortedRes= []
            state.products.forEach(obj =>{
                if (action.payload){
                    Object.keys(obj).forEach(key =>{
                        if(action.payload === key){
                            obj[key].forEach(e=>{
                                if(!state.roomsCurrentValue){
                                    if(+e.cost >= state.minCost && +e.cost <= state.maxCost && e.city.includes(state.cityCurrentValue) && e.district.includes(state.districtCurrentValue) && e.metro.includes(state.metroCurrentValue) && e.people.includes(state.bedSumCurrentValue)){
                                        sortedRes.push(e)
                                    }
                                } else if(+e.cost >= state.minCost && +e.cost <= state.maxCost && e.city.includes(state.cityCurrentValue) && e.rooms===state.roomsCurrentValue && e.district.includes(state.districtCurrentValue) && e.metro.includes(state.metroCurrentValue) && e.people.includes(state.bedSumCurrentValue)){
                                    sortedRes.push(e)
                                }
                            })
                        }
                    })
                } else{
                    Object.keys(obj).forEach(key =>{
                        obj[key].forEach(e=>{
                            if(!state.roomsCurrentValue){
                                if(+e.cost >= state.minCost && +e.cost <= state.maxCost && e.city.includes(state.cityCurrentValue) && e.district.includes(state.districtCurrentValue) && e.metro.includes(state.metroCurrentValue) && e.people.includes(state.bedSumCurrentValue)){
                                    sortedRes.push(e)
                                }
                            } else if(+e.cost >= state.minCost && +e.cost <= state.maxCost && e.city.includes(state.cityCurrentValue) && e.rooms===state.roomsCurrentValue && e.district.includes(state.districtCurrentValue) && e.metro.includes(state.metroCurrentValue) && e.people.includes(state.bedSumCurrentValue)){
                                sortedRes.push(e)
                            }
                        })
                    })
                }
            })
            state.productsLen = sortedRes.length

            // Сортировка массива
            switch (state.sortedValue) {
                case 'Сначала дешевые':
                    sortedRes.sort((a, b)=>{
                        return a.cost - b.cost
                    })
                    break
                case 'Сначала дорогие':
                    sortedRes.sort((a, b)=>{
                        return b.cost - a.cost
                    })
                    break
                default:
                    break
            }

            // Фильтрация по страницам
            let res = []
            let test = 0
            for (let i = 0; test < sortedRes.length; i++) {
                let obj = []
                for (let j = 0; j< state.productsLimit; j++) {
                    if(sortedRes[test]){
                        obj.push(sortedRes[test])
                        test++
                    }

                }
                res.push(obj)
            }
            state.sortedProducts = res
            state.currentPage = 1
        }

    }
})

export default main.reducer
export const {setCity, setRooms, setMinCost, setMaxCost, mainFilter, setDistrict, setMetro, resetFilter, setCurrentPage, setSortedValue, setLimit, likeHandler, setBedSum, checkboxHandler} = main.actions
