import {createSlice} from "@reduxjs/toolkit";
import flatImg from "../assets/img/flat-img.png";
import carImg from "../assets/img/mainBgCardsImg-4.png";
import cottageImg from "../assets/img/mainBgCardsImg-2.png";
import bathImg from "../assets/img/mainBgCardsImg-3.png";
import avatar from "../assets/img/avatar.png";

const main = createSlice({
    name: 'toolkit',
    initialState:{
        tabs:[{id:'flats', value:'Квартиры'}, {id:'cottages', value:'Котеджы и усадьбы'}, {id:'baths', value:'Бани и сауны'},  {id:'cars', value:'Авто на прокат'}],

        cityOption:[{id:1,value:'Минск'},{id:2,value:'Гомель'},{id:3,value:'Брест'},{id:4,value:'Витебск'},{id:5,value:'Гродно'}, {id:6,value:'Могилев'}],
        cityCurrentValue:'',

        roomsOption: [{id:1,value:1},{id:2,value:2},{id:3,value:3},{id:4,value:4},{id:5,value:5}],
        roomsCurrentValue:'',

        metroOption:[{id:1,value:'Грушевка'},{id:2,value:'Восход'},{id:3,value:'Пушкинская'},{id:4,value:'Партизанская'}],
        metroCurrentValue:'',

        districtOption:[{id:1,value:'Шабаны'},{id:2,value:'Запад'},{id:3,value:'Восток'},{id:4,value:'Малиновка'}],
        districtCurrentValue: '',

        productsLimit: 6,
        currentPage: 1,

        sortedOptions:[{id:1, value:'Сначала дешевые'}, {id:2, value: 'Сначала дорогие'}],
        sortedValue:'',


        bedSum:[{id:1, value:'1'}, {id:2, value:'2'}, {id:3, value:'3'}, {id:4, value:'4'}, {id:5, value:'5'},],
        bedSumCurrentValue:'',

        checkboxsMoreOption:[{id:1, value:'Газовая плита', bol:false},  {id:2, value:'Духовка', bol:false}, {id:3, value:'Кофеварка', bol:false}, {id:4, value:'Микроволновая печь ', bol:false}, {id:5, value:'Посуда', bol:false}, {id:6, value:'Посудомоечная машина', bol:false},],

        minCost:'',
        maxCost:'',


        productsLen: 0,
        sortedProducts:[],
        products: [{
            cars:[
                {id:1, obj:'cars', img:carImg, type:'Gold', rooms:1, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '10.00', metro:'Грушевка', district:'Малиновка', people:'1', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:2, obj:'cars', img:carImg, type:'Gold', rooms:2, city:'Гомель', like:false, location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Партизанская', district:'Запад', people:'2', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:3, obj:'cars', img:carImg, type:'Gold', rooms:3, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Грушевка', district:'Малиновка', people:'3', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:4, obj:'cars', img:carImg, type:'Gold', rooms:4, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Партизанская', district:'Запад', people:'4', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:5, obj:'cars', img:carImg, type:'Gold', rooms:5, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Пушкинская', district:'Восток', people:'5', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:6, obj:'cars', img:carImg, type:'Gold', rooms:1, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Грушевка', district:'Запад', people:'1', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:7, obj:'cars', img:carImg, type:'Gold', rooms:2, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '60.00', metro:'Партизанская', district:'Восток', people:'2', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:8, obj:'cars', img:carImg, type:'Gold', rooms:3, city:'Гомель', like:false, location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Пушкинская', district:'Запад', people:'3', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:9, obj:'cars', img:carImg, type:'Gold', rooms:4, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '70.00', metro:'Партизанская', district:'Шабаны', people:'4', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:10, obj:'cars', img:carImg, type:'Gold', rooms:5, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Восток', people:'5', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:11, obj:'cars', img:carImg, type:'Gold', rooms:1, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '85.00', metro:'Восход', district:'Запад', people:'1', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:12, obj:'cars', img:carImg, type:'Gold', rooms:2, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Пушкинская', district:'Шабаны', people:'2', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:13, obj:'cars', img:carImg, type:'Gold', rooms:3, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '120.00', metro:'Восход', district:'Восток', people:'3', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:14, obj:'cars', img:carImg, type:'Gold', rooms:4, city:'Гомель', like:false, location:'б-р Мулявина, д. 10', cost: '125.00', metro:'Грушевка', district:'Малиновка', people:'4', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:15, obj:'cars', img:carImg, type:'Gold', rooms:5, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '45.00', metro:'Пушкинская', district:'Шабаны', people:'5', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:16, obj:'cars', img:carImg, type:'Gold', rooms:1, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'1', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:17, obj:'cars', img:carImg, type:'Gold', rooms:2, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Пушкинская', district:'Шабаны', people:'2', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:18, obj:'cars', img:carImg, type:'Gold', rooms:3, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Партизанская', district:'Малиновка', people:'3', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:19, obj:'cars', img:carImg, type:'Gold', rooms:4, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '300.00', metro:'Восход', district:'Запад', people:'4', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:20, obj:'cars', img:carImg, type:'Gold', rooms:5, city:'Гомель', like:false, location:'б-р Мулявина, д. 10', cost: '650.00', metro:'Грушевка', district:'Малиновка', people:'5', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:21, obj:'cars', img:carImg, type:'Gold', rooms:1, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:22, obj:'cars', img:carImg, type:'Gold', rooms:2, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '70.00', metro:'Восход', district:'Малиновка', people:'2', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:23, obj:'cars', img:carImg, type:'Gold', rooms:3, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '70.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:24, obj:'cars', img:carImg, type:'Gold', rooms:4, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Восход', district:'Малиновка', people:'4', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},

            ],

            baths:[
                {id:25, obj:'baths',  img:bathImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Запад', people:'1', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:26, obj:'baths',  img:bathImg, type:'Gold', rooms:2, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Запад', people:'2', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:27, obj:'baths',  img:bathImg, type:'Gold', rooms:3, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Малиновка', people:'3', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:28, obj:'baths', img:bathImg, type:'Gold', rooms:4, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Шабаны', people:'4', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:29, obj:'baths', img:bathImg, type:'Gold', rooms:5, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Запад', people:'5', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:30, obj:'baths', img:bathImg, type:'Gold', rooms:1, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Запад', people:'1', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:31, obj:'baths',  img:bathImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Малиновка', people:'2', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:32, obj:'baths',  img:bathImg, type:'Gold', rooms:3, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Шабаны', people:'3', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:33, obj:'baths',  img:bathImg, type:'Gold', rooms:4, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Запад', people:'4', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:34, obj:'baths', img:bathImg, type:'Gold', rooms:5, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Запад', people:'5', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:35, obj:'baths', img:bathImg, type:'Gold', rooms:1, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Малиновка', people:'1', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:36, obj:'baths', img:bathImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:37, obj:'baths',  img:bathImg, type:'Gold', rooms:3, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:38, obj:'baths',  img:bathImg, type:'Gold', rooms:4, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Восток', people:'4', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:39, obj:'baths',  img:bathImg, type:'Gold', rooms:5, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Малиновка', people:'5', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:40, obj:'baths', img:bathImg, type:'Gold', rooms:1, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Шабаны', people:'1', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:41, obj:'baths', img:bathImg, type:'Gold', rooms:2, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Восток', people:'2', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:42, obj:'baths', img:bathImg, type:'Gold', rooms:3, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:43, obj:'baths',  img:bathImg, type:'Gold', rooms:4, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Малиновка', people:'4', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:44, obj:'baths',  img:bathImg, type:'Gold', rooms:5, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Шабаны', people:'5', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:45, obj:'baths',  img:bathImg, type:'Gold', rooms:1, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Восток', people:'1', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:46, obj:'baths', img:bathImg, type:'Gold', rooms:2, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Восток', people:'2', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:47, obj:'baths', img:bathImg, type:'Gold', rooms:3, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Малиновка', people:'3', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:48, obj:'baths', img:bathImg, type:'Gold', rooms:4, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Шабаны', people:'4', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},

            ],

            cottages:[
                {id:49, obj:'cottages', img:cottageImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'1', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:50, obj:'cottages', img:cottageImg, type:'Gold', rooms:2, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'2', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:51, obj:'cottages', img:cottageImg, type:'Gold', rooms:3, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'3', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:52, obj:'cottages', img:cottageImg, type:'Gold', rooms:4, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'4', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:53, obj:'cottages', img:cottageImg, type:'Gold', rooms:5, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'5', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:54, obj:'cottages', img:cottageImg, type:'Gold', rooms:1, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:55, obj:'cottages', img:cottageImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'2', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:56, obj:'cottages', img:cottageImg, type:'Gold', rooms:3, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'3', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:57, obj:'cottages', img:cottageImg, type:'Gold', rooms:4, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'4', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:58, obj:'cottages', img:cottageImg, type:'Gold', rooms:5, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'5', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:59, obj:'cottages', img:cottageImg, type:'Gold', rooms:1, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'1', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:60, obj:'cottages', img:cottageImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:61, obj:'cottages', img:cottageImg, type:'Gold', rooms:3, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:62, obj:'cottages', img:cottageImg, type:'Gold', rooms:4, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'4', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:63, obj:'cottages', img:cottageImg, type:'Gold', rooms:5, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'5', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:64, obj:'cottages', img:cottageImg, type:'Gold', rooms:1, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'1', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:65, obj:'cottages', img:cottageImg, type:'Gold', rooms:2, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'2', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:66, obj:'cottages', img:cottageImg, type:'Gold', rooms:3, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'3', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:67, obj:'cottages', img:cottageImg, type:'Gold', rooms:4, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'4', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:68, obj:'cottages', img:cottageImg, type:'Gold', rooms:5, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'5', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:69, obj:'cottages', img:cottageImg, type:'Gold', rooms:1, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:70, obj:'cottages', img:cottageImg, type:'Gold', rooms:2, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'2', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:71, obj:'cottages', img:cottageImg, type:'Gold', rooms:3, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:72, obj:'cottages', img:cottageImg, type:'Gold', rooms:4, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'4', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
            ],

            flats:[
                {id:73, obj:'flats', img:flatImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '15.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:74, obj:'flats', img:flatImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Запад', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:75, obj:'flats', img:flatImg, type:'Gold', rooms:3, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '45.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:76, obj:'flats', img:flatImg, type:'Gold', rooms:4, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Грушевка', district:'Малиновка', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:77, obj:'flats', img:flatImg, type:'Gold', rooms:5, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '60.00', metro:'Восход', district:'Шабаны', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:78, obj:'flats', img:flatImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Восход', district:'Запад', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:79, obj:'flats', img:flatImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Восток', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:80, obj:'flats', img:flatImg, type:'Gold', rooms:3, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '21.00', metro:'Восход', district:'Малиновка', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:81, obj:'flats', img:flatImg, type:'Gold', rooms:4, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Пушкинская', district:'Шабаны', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:82, obj:'flats', img:flatImg, type:'Gold', rooms:5, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '49.00', metro:'Пушкинская', district:'Запад', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:83, obj:'flats', img:flatImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Пушкинская', district:'Восток', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:84, obj:'flats', img:flatImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Пушкинская', district:'Малиновка', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:85, obj:'flats', img:flatImg, type:'Gold', rooms:3, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Партизанская', district:'Шабаны', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:86, obj:'flats', img:flatImg, type:'Gold', rooms:4, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Партизанская', district:'Запад', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:87, obj:'flats', img:flatImg, type:'Gold', rooms:5, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Партизанская', district:'Восток', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:88, obj:'flats', img:flatImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Партизанская', district:'Малиновка', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:89, obj:'flats', img:flatImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:90, obj:'flats', img:flatImg, type:'Gold', rooms:4, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:91, obj:'flats', img:flatImg, type:'Gold', rooms:5, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '49.00', metro:'Восход', district:'Запад', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:92, obj:'flats', img:flatImg, type:'Gold', rooms:1, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Пушкинская', district:'Восток', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:93, obj:'flats', img:flatImg, type:'Gold', rooms:2, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Малиновка', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:94, obj:'flats', img:flatImg, type:'Gold', rooms:3, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Партизанская', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:95, obj:'flats', img:flatImg, type:'Gold', rooms:4, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Партизанская', district:'Запад', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:96, obj:'flats', img:flatImg, type:'Gold', rooms:5, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Грушевка', district:'Восток', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:97, obj:'flats', img:flatImg, type:'Gold', rooms:1, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Партизанская', district:'Малиновка', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:98, obj:'flats', img:flatImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:99, obj:'flats', img:flatImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:100, obj:'flats', img:flatImg, type:'Gold', rooms:4, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:101, obj:'flats', img:flatImg, type:'Gold', rooms:5, city:'Гомель', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '49.00', metro:'Восход', district:'Запад', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:102, obj:'flats', img:flatImg, type:'Gold', rooms:1, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Пушкинская', district:'Восток', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:103, obj:'flats', img:flatImg, type:'Gold', rooms:2, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Малиновка', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:104, obj:'flats', img:flatImg, type:'Gold', rooms:3, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Партизанская', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:105, obj:'flats', img:flatImg, type:'Gold', rooms:4, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Партизанская', district:'Запад', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:106, obj:'flats', img:flatImg, type:'Gold', rooms:5, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Грушевка', district:'Восток', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:107, obj:'flats', img:flatImg, type:'Gold', rooms:1, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Партизанская', district:'Малиновка', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:108, obj:'flats', img:flatImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:109, obj:'flats', img:flatImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},

            ],
        }],

    },
    reducers: {

        setBedSum(state, action){
            state.bedSumCurrentValue = action.payload
        },

        checkboxHandler(state, action){
            state.checkboxsMoreOption.forEach(obj =>{
                if(obj.value.includes(action.payload)){
                    obj.bol = !obj.bol

                }
            })
        },

        likeHandler(state, action){
            state.products.forEach(obj=>{
                Object.keys(obj).forEach(key=>{
                    if(key === action.payload.type){
                        obj[key].forEach(e=>{
                            if (e.id === action.payload.id){
                                e.like = !e.like
                            }
                        })
                    }
                })
            })
        },
        setCity(state, action){
            state.cityCurrentValue = action.payload

        },
        setRooms(state, action){
            state.roomsCurrentValue = action.payload
        },
        setMinCost(state, action){
            if(action.payload<0 || action.payload > 1000){
                return
            }
            state.minCost = action.payload
        },
        setMaxCost(state, action){
            if(action.payload<0 || action.payload > 1000){
                return
            }
            state.maxCost = action.payload
        },
        setDistrict(state, action){
            state.districtCurrentValue = action.payload
        },
        setMetro(state, action){
            state.metroCurrentValue = action.payload
        },
        setCurrentPage(state, action){
            state.currentPage = action.payload
            window.scrollTo(0, 0)
        },
        setSortedValue(state, action){
            state.sortedValue = action.payload
        },

        setLimit(state, action){
            state.productsLimit = action.payload
        },
        resetFilter(state){
            state.sortedValue = ''
            state.roomsCurrentValue = ''
            state.minCost = ''
            state.maxCost = ''
            state.districtCurrentValue = ''
            state.metroCurrentValue = ''
            state.bedSumCurrentValue = ''
            state.checkboxsMoreOption.forEach(e=>{
                e.bol = false
            })
        },

        mainFilter(state, action){
            // Условия для высчитывания стоимости
            while(state.minCost > state.maxCost ){
                state.maxCost = +state.maxCost + 100
            }
            if(state.minCost === ''){
                state.minCost=0
            }
            if(state.maxCost === ''){
                state.maxCost = 1000
            }


            //Основная фильтрация
            let sortedRes= []
            state.products.forEach(obj =>{
                if (action.payload){
                    Object.keys(obj).forEach(key =>{
                        if(action.payload === key){
                            obj[key].forEach(e=>{
                                if(!state.roomsCurrentValue){
                                    if(+e.cost >= state.minCost && +e.cost <= state.maxCost && e.city.includes(state.cityCurrentValue) && e.district.includes(state.districtCurrentValue) && e.metro.includes(state.metroCurrentValue) && e.people.includes(state.bedSumCurrentValue)){
                                        sortedRes.push(e)
                                    }
                                } else if(+e.cost >= state.minCost && +e.cost <= state.maxCost && e.city.includes(state.cityCurrentValue) && e.rooms===state.roomsCurrentValue && e.district.includes(state.districtCurrentValue) && e.metro.includes(state.metroCurrentValue) && e.people.includes(state.bedSumCurrentValue)){
                                    sortedRes.push(e)
                                }
                            })
                        }
                    })
                } else{
                    Object.keys(obj).forEach(key =>{
                        obj[key].forEach(e=>{
                            if(!state.roomsCurrentValue){
                                if(+e.cost >= state.minCost && +e.cost <= state.maxCost && e.city.includes(state.cityCurrentValue) && e.district.includes(state.districtCurrentValue) && e.metro.includes(state.metroCurrentValue) && e.people.includes(state.bedSumCurrentValue)){
                                    sortedRes.push(e)
                                }
                            } else if(+e.cost >= state.minCost && +e.cost <= state.maxCost && e.city.includes(state.cityCurrentValue) && e.rooms===state.roomsCurrentValue && e.district.includes(state.districtCurrentValue) && e.metro.includes(state.metroCurrentValue) && e.people.includes(state.bedSumCurrentValue)){
                                sortedRes.push(e)
                            }
                        })
                    })
                }
            })
            state.productsLen = sortedRes.length

            // Сортировка массива
            switch (state.sortedValue) {
                case 'Сначала дешевые':
                    sortedRes.sort((a, b)=>{
                        return a.cost - b.cost
                    })
                    break
                case 'Сначала дорогие':
                    sortedRes.sort((a, b)=>{
                        return b.cost - a.cost
                    })
                    break
                default:
                    break
            }

            // Фильтрация по страницам
            let res = []
            let test = 0
            for (let i = 0; test < sortedRes.length; i++) {
                let obj = []
                for (let j = 0; j< state.productsLimit; j++) {
                    if(sortedRes[test]){
                        obj.push(sortedRes[test])
                        test++
                    }

                }
                res.push(obj)
            }
            state.sortedProducts = res
            state.currentPage = 1
        }

    }
})

export default main.reducer
export const {setCity, setRooms, setMinCost, setMaxCost, mainFilter, setDistrict, setMetro, resetFilter, setCurrentPage, setSortedValue, setLimit, likeHandler, setBedSum, checkboxHandler} = main.actions
