import {createSlice} from "@reduxjs/toolkit";
import flatImg from "../assets/img/flat-img.png";
import carImg from "../assets/img/mainBgCardsImg-4.png";
import cottageImg from "../assets/img/mainBgCardsImg-2.png";
import bathImg from "../assets/img/mainBgCardsImg-3.png";
import avatar from "../assets/img/avatar.png";

const main = createSlice({
    name: 'toolkit',
    initialState:{
        tabs:[{id:'flats', value:'Квартиры'}, {id:'cottages', value:'Котеджы и усадьбы'}, {id:'baths', value:'Бани и сауны'},  {id:'cars', value:'Авто на прокат'}],

        cityOption:[{id:1,value:'Минск'},{id:2,value:'Гомеле'},{id:3,value:'Бресте'},{id:4,value:'Витебске'},{id:5,value:'Гродно'}, {id:6,value:'Могилеве'}],
        cityCurrentValue:'',

        roomsOption: [{id:1,value:1},{id:2,value:2},{id:3,value:3},{id:4,value:4},{id:5,value:5}],
        roomsCurrentValue:'',

        metroOption:[{id:1,value:'Грушевка'},{id:2,value:'Восход'},{id:3,value:'Пушкинская'},{id:4,value:'Партизанская'}],
        metroCurrentValue:'',

        districtOption:[{id:1,value:'Шабаны'},{id:2,value:'Запад'},{id:3,value:'Восток'},{id:4,value:'Малиновка'}],
        districtCurrentValue: '',


        minCost:'',
        maxCost:'',

        // cityValue:true,
        products: [{
            cars:[
                {id:1, img:carImg, type:'Gold', rooms:1, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '10.00', metro:'Грушевка', district:'Малиновка', people:'1', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:2, img:carImg, type:'Gold', rooms:2, city:'Гомеле', like:false, location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Партизанская', district:'Запад', people:'2', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:3, img:carImg, type:'Gold', rooms:3, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Грушевка', district:'Малиновка', people:'3', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:4, img:carImg, type:'Gold', rooms:4, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Партизанская', district:'Запад', people:'4', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:5, img:carImg, type:'Gold', rooms:5, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Пушкинская', district:'Восток', people:'5', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:6, img:carImg, type:'Gold', rooms:1, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Грушевка', district:'Запад', people:'1', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:7, img:carImg, type:'Gold', rooms:2, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '60.00', metro:'Партизанская', district:'Восток', people:'2', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:8, img:carImg, type:'Gold', rooms:3, city:'Гомеле', like:false, location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Пушкинская', district:'Запад', people:'3', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:9, img:carImg, type:'Gold', rooms:4, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '70.00', metro:'Партизанская', district:'Шабаны', people:'4', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:10, img:carImg, type:'Gold', rooms:5, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Восток', people:'5', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:11, img:carImg, type:'Gold', rooms:1, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '85.00', metro:'Восход', district:'Запад', people:'1', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:12, img:carImg, type:'Gold', rooms:2, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Пушкинская', district:'Шабаны', people:'2', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:13, img:carImg, type:'Gold', rooms:3, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '120.00', metro:'Восход', district:'Восток', people:'3', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:14, img:carImg, type:'Gold', rooms:4, city:'Гомеле', like:false, location:'б-р Мулявина, д. 10', cost: '125.00', metro:'Грушевка', district:'Малиновка', people:'4', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:15, img:carImg, type:'Gold', rooms:5, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '45.00', metro:'Пушкинская', district:'Шабаны', people:'5', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:16, img:carImg, type:'Gold', rooms:1, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'1', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:17, img:carImg, type:'Gold', rooms:2, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Пушкинская', district:'Шабаны', people:'2', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:18, img:carImg, type:'Gold', rooms:3, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Партизанская', district:'Малиновка', people:'3', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:19, img:carImg, type:'Gold', rooms:4, city:'Минск', like:false, location:'б-р Мулявина, д. 10', cost: '300.00', metro:'Восход', district:'Запад', people:'4', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:20, img:carImg, type:'Gold', rooms:5, city:'Гомеле', like:false, location:'б-р Мулявина, д. 10', cost: '650.00', metro:'Грушевка', district:'Малиновка', people:'5', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:21, img:carImg, type:'Gold', rooms:1, city:'Бресте', like:false, location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:22, img:carImg, type:'Gold', rooms:2, city:'Витебске', like:false, location:'б-р Мулявина, д. 10', cost: '70.00', metro:'Восход', district:'Малиновка', people:'2', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:23, img:carImg, type:'Gold', rooms:3, city:'Гродно', like:false, location:'б-р Мулявина, д. 10', cost: '70.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:24, img:carImg, type:'Gold', rooms:4, city:'Могилеве', like:false, location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Восход', district:'Малиновка', people:'4', title: '-местная. машина', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},

            ],

            baths:[
                {id:25, img:bathImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Запад', people:'1', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:26, img:bathImg, type:'Gold', rooms:2, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Запад', people:'2', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:27, img:bathImg, type:'Gold', rooms:3, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Малиновка', people:'3', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:28,img:bathImg, type:'Gold', rooms:4, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Шабаны', people:'4', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:29,img:bathImg, type:'Gold', rooms:5, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Запад', people:'5', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:30,img:bathImg, type:'Gold', rooms:1, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Запад', people:'1', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:31, img:bathImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Малиновка', people:'2', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:32, img:bathImg, type:'Gold', rooms:3, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Шабаны', people:'3', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:33, img:bathImg, type:'Gold', rooms:4, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Запад', people:'4', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:34,img:bathImg, type:'Gold', rooms:5, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Запад', people:'5', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:35,img:bathImg, type:'Gold', rooms:1, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Малиновка', people:'1', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:36,img:bathImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:37, img:bathImg, type:'Gold', rooms:3, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:38, img:bathImg, type:'Gold', rooms:4, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Восток', people:'4', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:39, img:bathImg, type:'Gold', rooms:5, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Малиновка', people:'5', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:40,img:bathImg, type:'Gold', rooms:1, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Шабаны', people:'1', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:41,img:bathImg, type:'Gold', rooms:2, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Восток', people:'2', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:42,img:bathImg, type:'Gold', rooms:3, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:43, img:bathImg, type:'Gold', rooms:4, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Грушевка', district:'Малиновка', people:'4', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:44, img:bathImg, type:'Gold', rooms:5, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Шабаны', people:'5', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:45, img:bathImg, type:'Gold', rooms:1, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Пушкинская', district:'Восток', people:'1', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:46,img:bathImg, type:'Gold', rooms:2, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '90.00', metro:'Партизанская', district:'Восток', people:'2', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:47,img:bathImg, type:'Gold', rooms:3, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Грушевка', district:'Малиновка', people:'3', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:48,img:bathImg, type:'Gold', rooms:4, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Грушевка', district:'Шабаны', people:'4', title: '-комн. баня', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},

            ],

            cottages:[
                {id:49, img:cottageImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'1', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:50, img:cottageImg, type:'Gold', rooms:2, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'2', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:51, img:cottageImg, type:'Gold', rooms:3, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'3', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:52, img:cottageImg, type:'Gold', rooms:4, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'4', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:53, img:cottageImg, type:'Gold', rooms:5, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'5', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:54, img:cottageImg, type:'Gold', rooms:1, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:55, img:cottageImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'2', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:56, img:cottageImg, type:'Gold', rooms:3, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'3', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:57, img:cottageImg, type:'Gold', rooms:4, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'4', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:58, img:cottageImg, type:'Gold', rooms:5, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'5', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:59, img:cottageImg, type:'Gold', rooms:1, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'1', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:60, img:cottageImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:61, img:cottageImg, type:'Gold', rooms:3, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:62, img:cottageImg, type:'Gold', rooms:4, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'4', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:63, img:cottageImg, type:'Gold', rooms:5, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'5', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:64, img:cottageImg, type:'Gold', rooms:1, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'1', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:65, img:cottageImg, type:'Gold', rooms:2, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'2', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:66, img:cottageImg, type:'Gold', rooms:3, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'3', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:67, img:cottageImg, type:'Gold', rooms:4, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Восток', people:'4', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:68, img:cottageImg, type:'Gold', rooms:5, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '25.00', metro:'Партизанская', district:'Малиновка', people:'5', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:69, img:cottageImg, type:'Gold', rooms:1, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '40.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:70, img:cottageImg, type:'Gold', rooms:2, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Запад', people:'2', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:71, img:cottageImg, type:'Gold', rooms:3, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:72, img:cottageImg, type:'Gold', rooms:4, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Грушевка', district:'Шабаны', people:'4', title: '-комн. коттедж', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
            ],

            flats:[
                {id:73, img:flatImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '15.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:74, img:flatImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '35.00', metro:'Грушевка', district:'Запад', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:75, img:flatImg, type:'Gold', rooms:3, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '45.00', metro:'Грушевка', district:'Восток', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:76, img:flatImg, type:'Gold', rooms:4, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '55.00', metro:'Грушевка', district:'Малиновка', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:77, img:flatImg, type:'Gold', rooms:5, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '60.00', metro:'Восход', district:'Шабаны', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:78, img:flatImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Восход', district:'Запад', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:79, img:flatImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '30.00', metro:'Восход', district:'Восток', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:80, img:flatImg, type:'Gold', rooms:3, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '21.00', metro:'Восход', district:'Малиновка', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:81, img:flatImg, type:'Gold', rooms:4, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Пушкинская', district:'Шабаны', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:82, img:flatImg, type:'Gold', rooms:5, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '49.00', metro:'Пушкинская', district:'Запад', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:83, img:flatImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Пушкинская', district:'Восток', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:84, img:flatImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Пушкинская', district:'Малиновка', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:85, img:flatImg, type:'Gold', rooms:3, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Партизанская', district:'Шабаны', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:86, img:flatImg, type:'Gold', rooms:4, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Партизанская', district:'Запад', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:87, img:flatImg, type:'Gold', rooms:5, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Партизанская', district:'Восток', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:88, img:flatImg, type:'Gold', rooms:1, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Партизанская', district:'Малиновка', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:89, img:flatImg, type:'Gold', rooms:2, city:'Минск', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:90, img:flatImg, type:'Gold', rooms:4, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:91, img:flatImg, type:'Gold', rooms:5, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '49.00', metro:'Восход', district:'Запад', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:92, img:flatImg, type:'Gold', rooms:1, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Пушкинская', district:'Восток', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:93, img:flatImg, type:'Gold', rooms:2, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Малиновка', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:94, img:flatImg, type:'Gold', rooms:3, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Партизанская', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:95, img:flatImg, type:'Gold', rooms:4, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Партизанская', district:'Запад', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:96, img:flatImg, type:'Gold', rooms:5, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Грушевка', district:'Восток', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:97, img:flatImg, type:'Gold', rooms:1, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Партизанская', district:'Малиновка', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:98, img:flatImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:99, img:flatImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:100, img:flatImg, type:'Gold', rooms:4, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '34.00', metro:'Пушкинская', district:'Шабаны', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:101, img:flatImg, type:'Gold', rooms:5, city:'Гомеле', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '49.00', metro:'Восход', district:'Запад', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:102, img:flatImg, type:'Gold', rooms:1, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Пушкинская', district:'Восток', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:103, img:flatImg, type:'Gold', rooms:2, city:'Бресте', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Восход', district:'Малиновка', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:104, img:flatImg, type:'Gold', rooms:3, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '50.00', metro:'Партизанская', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:105, img:flatImg, type:'Gold', rooms:4, city:'Витебске', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '80.00', metro:'Партизанская', district:'Запад', people:'3', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:106, img:flatImg, type:'Gold', rooms:5, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '65.00', metro:'Грушевка', district:'Восток', people:'4', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:107, img:flatImg, type:'Gold', rooms:1, city:'Гродно', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '100.00', metro:'Партизанская', district:'Малиновка', people:'5', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:108, img:flatImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'1', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},
                {id:109, img:flatImg, type:'Gold', rooms:2, city:'Могилеве', like:false, size:'179 м²',location:'б-р Мулявина, д. 10', cost: '20.00', metro:'Грушевка', district:'Шабаны', people:'2', title: '-комн. апартаменты', body: 'Большая четырехкомнатная студия! Большая джкакузи на двоих, на теливизоре есть приложение Megogo, YouTube, Smart TV, сможете выбрать фильм по вкусу!) Цена зависит от количества проживающих, уточняйте, пожалуйста, по телефону! В пяти минутах ходьбы Минск-Арена,  ...', profile: {name: 'Dmitriy', viber: 'https://www.viber.com/ru/', whatsUpp:'https://www.whatsapp.com/?lang=ru', avatar:avatar, phone:'+375 (29) 291-14-44', city:'Владимир', email: 'vladimir6234@tut.by'},},

            ],
        }],

    },
    reducers: {
        setCity(state, action){
            state.cityCurrentValue = action.payload
            console.log(state.cityCurrentValue)
        },
        setRooms(state, action){
            state.roomsCurrentValue = action.payload
            console.log(state.roomsCurrentValue)
        },
        setMinCost(state, action){
            if(action.payload<0 || action.payload > 1000){
                return
            }
            state.minCost = action.payload
            console.log(state.minCost)
        },
        setMaxCost(state, action){
            if(action.payload<0 || action.payload > 1000){
                return
            }
            state.maxCost = action.payload
            console.log(state.maxCost)
        },
        setDistrict(state, action){
            state.districtCurrentValue = action.payload
            console.log(state.districtCurrentValue)
        },
        setMetro(state, action){
            state.metroCurrentValue = action.payload
            console.log(state.metroCurrentValue)
        },

        mainFilter(state){
            while(state.minCost > state.maxCost ){
                state.maxCost = +state.maxCost + 100
            }
            if(state.minCost === ''){
                state.minCost=0
            }
            if(state.maxCost === ''){
                state.maxCost = 1000
            }

        }

    }
})

export default main.reducer
export const {setCity, setRooms, setMinCost, setMaxCost, mainFilter, setDistrict, setMetro} = main.actions
