name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish Docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: Grog-xd/SDAEM-BY
          registry: docker.pkg.github.com

      - name: Starting Node js
        uses: actions/setup-node@v3

      - name: install modules
        run: npm install

      - name: lint test
        run: npm run lint

      - name: unit test
        run: npm run test

      - name: build project
        run: npm run build




